# tasks file for VirtualBox
# installation process according to
# https://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/
---
  # Download VirtualBox RHEL Repo Files
  - name: Add VirtualBox repo
    get_url: url={{ vb_repo_url }} dest={{ yum_repo_path }} mode=0440
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Update latest packages
  - name: Update packages
    yum: name="*" state="latest"
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Check if kernel version is up to date
  - name: Check for kernel version
    shell: LAST_KERNEL=`rpm -qa kernel | sort -V | tail -n 1 | sed 's/.*kernel-//'`; CURRENT_KERNEL=`uname -r`; if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
    ignore_errors: true
    register: reboot_hint
    changed_when: reboot_hint.stdout.find("reboot") != -1
    notify:
      - reboot_server
      - wait_for_server
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Imediately flush handlers
  - meta: flush_handlers

  # Download and install EPEL for Centos/RHEL version 7
  - name: Download EPEL Repo - Centos/RHEL 7
    get_url: url={{ epel_repo_url }} dest={{ epel_path }}
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  - name: Install EPEL Repo - Centos/RHEL 7
    command: rpm -ivh {{ epel_path }} creates=/etc/yum.repos.d/epel.repo
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # - name: Download and install EPEL Repo - Centos/RHEL 7
  #   yum: name={{ epel_repo_url }} state=present
  #   when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Download and install dependency packages for Centos/RHEL version 7
  - name: Install dependencies
    yum: name={{ item }} state=present
    with_items:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Download and install VirtualBox Latest Version for Centos/RHEL version 7
  - name: Install VirtualBox
    yum: name={{ virtualbox_rpm_package }} state=present
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Rebuild kernel modules
  - name: Rebuild kernel modules
    command: /usr/lib/virtualbox/vboxdrv.sh setup
    become: yes
    become_method: sudo
    when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

  # Add connected user (via ssh) to vboxusers group
  - name: Add VirtualBox user(s) to user groups
    user: name={{ ansible_ssh_user }} group=vboxusers
